<?
$bdName="공지사항";
$bdGroup="";
$bdSkin="default";
$bdAlign="center";
$bdWidth="96%";
$bdStrlen="";
$bdPageNum="20";
$bdNew="168";
$bdHot="";
$bdNoticeList="";
$bdLvlL="";
$bdLvlR="";
$bdLvlC="100";
$bdLvlW="100";
$bdIp="";
$bdIpAsterisk="";
$bdTypeView="2";
$bdUseLink="";
$bdUseFile="on";
$bdMaxSize="";
$bdTypeMail="";
$bdHeader="<!-- 상단이미지 || 현재위치 -->
<TABLE width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">
<TR>
	<td class=\"path\">HOME > <b>공지사항</b></td>
</TR>
</TABLE>";
$bdFooter="";
$bdUseSubSpeech="";
$bdSubSpeech="";
$bdUseComment="on";
$bdSearchMode="0";
$bdField="";
$bdImg="";
$bdColor="";
$bdPrnType="1";
$bdListImgCntW="5";
$bdListImgCntH="4";
$bdListImgSizeW="100";
$bdListImgSizeH="100";
$bdListImg="";
$bdUserDsp="0";
$bdAdminDsp="0";
$bdSpamComment="3";
$bdSpamBoard="3";
$bdSecretChk="2";
$bdTitleCChk="on";
$bdTitleSChk="on";
$bdTitleBChk="on";
$bdEmailNo="on";
$bdHomepageNo="on";
?>